### ISSUE TITLE
Section Bottom

### ISSUE THREAD

**Issue by amol-anand** [amol-anand/adobe-franklin-demo#4]
**Section Bottom** _(where the circular background ends)_
![merative-section-bottom](https://user-images.githubusercontent.com/7074782/199854932-b2a194db-67cf-4401-a3e2-5257e5bbcab1.png)

**Comment by kunwarsaluja** [comment]
https://github.com/amol-anand/adobe-franklin-demo/pull/16 was just for section-top, I think we should re-open this issue.

Ill submit the PR separately for this issue (section-bottom)
